https-portal:
  image: index.docker.io/steveltn/https-portal:1
  ports:
  - 80:80
  - 443:443
  links:
  - node
  environment:
    DOMAINS: api.redrock.atowerlight.cn -> http://node:3000
    STAGE: production
  volumes:
  - /home/docker/https-portal:/var/lib/https-portal
node:
  image: daocloud.io/houzhenhong/redrock:latest
  links:
  - redis
  - mongo
  expose:
  - 3000
  restart: always
  environment:
  - GEETEST_ID=xxx
  - GEETEST_KEY=xxx
  - MONGO=mongodb://mongo:27017/weibotest
  - UPYUN_BUCKET=redrock
  - REDIS=redis://redis:6379/1
  - UPYUN_URL=https://upyun.redrock.atowerlight.cn
  - UPYUN_PASSWORD=xxxx
  - UPYUN_OPERATOR=xxxx
  - FE_URL=https://redrock.atowerlight.cn
redis:
  image: daocloud.io/library/redis:3.2.9-alpine
  volumes:
  - /home/docker/redis:/data
  restart: always
mongo:
  image: mvertes/alpine-mongo:4.0.5-0
  volumes:
  - /home/docker/mongo/db:/data/db
  - /home/docker/mongo/configdb:/data/configdb
  restart: always
