# Generated by Django 2.1.2 on 2019-01-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='标题')),
                ('src', models.CharField(blank=True, max_length=10, null=True, verbose_name='链接')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='icon')),
            ],
        ),
    ]
