# Generated by Django 2.1.2 on 2019-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboapp', '0004_auto_20190127_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='标签名'),
        ),
    ]
