# Generated by Django 2.1.2 on 2019-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboapp', '0005_auto_20190127_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='link',
            name='src',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='链接'),
        ),
    ]
