# Generated by Django 2.1.2 on 2019-02-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weiboapp', '0012_auto_20190201_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='weiboapp.UserProfile'),
        ),
    ]
