# Generated by Django 2.1.2 on 2019-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboapp', '0013_auto_20190201_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(default=1, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
